// <auto-generated />
namespace NissanCartTest01.WebUi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Migrar21th : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Migrar21th));
        
        string IMigrationMetadata.Id
        {
            get { return "201710012000456_Migrar21th"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
